version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: node_app
    restart: on-failure
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/form
    ports:
      - "3000:3000"
    depends_on:
      - mongo
